channels:
  - pytorch
  - conda-forge
  - anaconda
  - oxfordcontrol
  - defaults
dependencies:
  - numpy
  - pytorch
  - pillow
  - matplotlib
  - sk-video
  - torchvision
  - pip:
    - opencv-python
    - utils

