channels:
  - pytorch
  - conda-forge
  - anaconda
  - oxfordcontrol
  - defaults
dependencies:
  - backcall
  - blas
  - ca-certificates
  - certifi
  - colorama
  - cudatoolkit
  - cycler
  - decorator
  - freetype
  - hdf5
  - icc_rt
  - icu
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - libblas
  - libcblas
  - liblapack
  - libopencv
  - libpng
  - libsodium
  - libtiff
  - libuv
  - lz4-c
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msys2-conda-epoch
  - ninja
  - numpy
  - numpy-base
  - olefile
  - opencv
  - openssl
  - parso
  - pickleshare
  - pillow
  - pip
  - prompt-toolkit
  - py-opencv
  - pygments
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - python-utils
  - python_abi
  - pytorch
  - pywin32
  - pyzmq
  - qt
  - scipy
  - setuptools
  - sip
  - six
  - sk-video
  - sqlite
  - tk
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - vc
  - vs2015_runtime
  - wcwidth
  - wheel
  - wincertstore
  - xz
  - zeromq
  - zlib
  - zstd
  - pip:
    - utils

