channels:
  - pytorch
  - conda-forge
  - anaconda
  - oxfordcontrol
  - defaults
dependencies:
  - numpy
  - pytorch
  - pillow
  - matplotlib
  - torchvision
  - mesa-libgl-cos6-x86_64
  - pip:
    - sk-video
    - opencv-python
    - utils

